server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/proactive
    username: postgres
    password: root